//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use crate::models;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_vault")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::encrypted_vault::Id,
    pub iv: models::encrypted_vault::IV,
    pub tag: models::encrypted_vault::Tag,
    pub ver: models::encrypted_vault::Version,
    pub algo: super::sea_orm_active_enums::EncryptionAlgo,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::encrypted_blobs::Entity")]
    EncryptedBlobs,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
}

impl Related<super::encrypted_blobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncryptedBlobs.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
