//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use nutype::nutype;
use sea_orm::entity::prelude::*;
use crate::models;

#[nutype(
    const_fn,
    derive(
        Debug,
        PartialEq,
        Eq,
        Copy,
        Clone,
        Serialize,
        Deserialize,
        Hash,
        Deref,
        Display,
        FromStr
    ),
    derive_unchecked(DeriveValueType)
)]
pub struct Id(models::encrypted_vault::Id);

impl sea_orm::TryFromU64 for Id {
    fn try_from_u64(n: u64) -> Result<Self, DbErr> {
        use std::convert::TryInto;
        Ok(Self::new(models::encrypted_vault::Id::new(
            n.try_into().map_err(|e| DbErr::TryIntoErr {
                from: "u64",
                into: "Id",
                source: std::sync::Arc::new(e),
            })?,
        )))
    }
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub data: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encrypted_vault::Entity",
        from = "Column::Id",
        to = "super::encrypted_vault::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EncryptedVault,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::folders::Entity")]
    Folders,
}

impl Related<super::encrypted_vault::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncryptedVault.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
