//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use tinystr::TinyAsciiStr;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::macros::tiny_str_sea_orm_derive;
use crate::models;


tiny_str_sea_orm_derive!(models::folders::PublicId as 8: |s| { Self::new(s) });

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::folders::Id,
    #[sea_orm(unique)]
    pub public_id: models::folders::PublicId,
    pub encrypted_name: super::encrypted_blobs::Id,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encrypted_blobs::Entity",
        from = "Column::EncryptedName",
        to = "super::encrypted_blobs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EncryptedBlobs,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
}

impl Related<super::encrypted_blobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncryptedBlobs.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
