//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::EncryptionAlgo;
use sea_orm::entity::prelude::*;
use crate::models;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_vault")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::encrypted_vault::Id,
    pub iv: models::encrypted_vault::IV,
    pub tag: models::encrypted_vault::Tag,
    pub ver: models::encrypted_vault::Version,
    pub algo: EncryptionAlgo,
    #[sea_orm(has_one)]
    pub encrypted_blobs: HasOne<super::encrypted_blobs::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl From<models::encrypted_vault::Model> for ActiveModelEx {
    fn from(value: models::encrypted_vault::Model) -> Self {
        ActiveModel::builder()
            .set_iv(value.iv)
            .set_tag(value.tag)
            .set_ver(value.ver)
            .set_algo(value.algo)
    }
}

impl From<models::encrypted_vault::NewVault> for ActiveModelEx {
    fn from(value: models::encrypted_vault::NewVault) -> Self {
        ActiveModel::builder()
            .set_iv(value.iv)
            .set_tag(value.tag)
            .set_ver(value.ver)
            .set_algo(value.algo)
    }
}

impl TryFrom<ActiveModelEx> for models::encrypted_vault::Model {
    type Error = ();

    fn try_from(mut value: ActiveModelEx) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id.take().ok_or(())?,
            iv: value.iv.take().ok_or(())?,
            tag: value.tag.take().ok_or(())?,
            ver: value.ver.take().ok_or(())?,
            algo: value.algo.take().ok_or(())?.into(),
        })
    }
}