//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::models;
use nutype::nutype;
use sea_orm::entity::prelude::*;
use crate::persistence::FromActiveModelExError;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_blobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::encrypted_blobs::Id,
    pub vault_id: models::encrypted_vault::Id,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub data: Vec<u8>,
    #[sea_orm(
        belongs_to,
        from = "vault_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_vault: HasOne<super::encrypted_vault::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(has_many)]
    pub folders: HasMany<super::folders::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl From<models::encrypted_blobs::Model> for ActiveModelEx {
    fn from(value: models::encrypted_blobs::Model) -> Self {
        ActiveModel::builder()
            .set_data(value.data)
            .set_encrypted_vault(value.meta)
    }
}

impl From<models::encrypted_blobs::NewBlob> for ActiveModelEx {
    fn from(value: models::encrypted_blobs::NewBlob) -> Self {
        ActiveModel::builder()
            .set_encrypted_vault(value.new_vault)
            .set_data(value.data)
    }
} 

impl TryFrom<ActiveModelEx> for models::encrypted_blobs::Model {
    type Error = FromActiveModelExError;

    fn try_from(mut value: ActiveModelEx) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id.take().ok_or(FromActiveModelExError::ValueNotProvided)?,
            meta: value.encrypted_vault.take().ok_or(FromActiveModelExError::ValueNotProvided)?.try_into()?,
            data: value.data.take().ok_or(FromActiveModelExError::ValueNotProvided)?.into(),
        })
    }
}
