//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::EncryptionAlgo;
use sea_orm::entity::prelude::*;
use crate::models;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_vault")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::encrypted_vault::Id,
    pub iv: models::encrypted_vault::IV,
    pub tag: models::encrypted_vault::Tag,
    pub ver: models::encrypted_vault::Version,
    pub algo: EncryptionAlgo,
    #[sea_orm(has_one)]
    pub encrypted_blobs: HasOne<super::encrypted_blobs::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
