//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::models;
use nutype::nutype;
use sea_orm::entity::prelude::*;

#[nutype(
    const_fn,
    derive(
        Debug,
        PartialEq,
        Eq,
        Copy,
        Clone,
        Serialize,
        Deserialize,
        Hash,
        Deref,
        Display,
        FromStr
    ),
    derive_unchecked(DeriveValueType)
)]
pub struct Id(models::encrypted_vault::Id);

impl sea_orm::TryFromU64 for Id {
    fn try_from_u64(n: u64) -> Result<Self, DbErr> {
        use std::convert::TryInto;
        Ok(Self::new(models::encrypted_vault::Id::new(
            n.try_into().map_err(|e| DbErr::TryIntoErr {
                from: "u64",
                into: "Id",
                source: std::sync::Arc::new(e),
            })?,
        )))
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "encrypted_blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Id,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub data: Vec<u8>,
    #[sea_orm(
        belongs_to,
        from = "id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_vault: HasOne<super::encrypted_vault::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(has_many)]
    pub folders: HasMany<super::folders::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl From<models::encrypted_blobs::Model> for ActiveModelEx {
    fn from(value: models::encrypted_blobs::Model) -> Self {
        ActiveModel::builder()
            .set_data(value.data)
            .set_encrypted_vault(value.meta)
    }
}

impl From<models::encrypted_blobs::NewBlob> for ActiveModelEx {
    fn from(value: models::encrypted_blobs::NewBlob) -> Self {
        ActiveModel::builder()
            .set_encrypted_vault(value.new_vault)
            .set_data(value.data)
    }
} 

impl TryFrom<ActiveModelEx> for models::encrypted_blobs::Model {
    type Error = ();

    fn try_from(mut value: ActiveModelEx) -> Result<Self, Self::Error> {
        Ok(Self {
            meta: value.encrypted_vault.take().ok_or(())?.try_into()?,
            data: value.data.take().ok_or(())?.into(),
        })
    }
}
