//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::macros::tiny_str_sea_orm_derive;
use crate::models;
use sea_orm::entity::prelude::*;
use sea_orm::LinkDef;
use tinystr::TinyAsciiStr;

tiny_str_sea_orm_derive!(models::files::PublicId as 16: |s| { Self::new(s) });

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::files::Id,
    #[sea_orm(unique)]
    pub public_id: models::files::PublicId,
    pub folder_id: models::folders::Id,
    pub data_meta_id: models::encrypted_vault::Id,
    pub meta_id: super::encrypted_blobs::Id,
    #[sea_orm(unique)]
    pub storage_path: models::files::StoragePath,
    pub file_size: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encrypted_blobs::Entity",
        from = "Column::MetaId",
        to = "super::encrypted_blobs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EncryptedBlobs,
    #[sea_orm(
        belongs_to = "super::encrypted_vault::Entity",
        from = "Column::DataMetaId",
        to = "super::encrypted_vault::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EncryptedVault,
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Folders,
}

impl Related<super::encrypted_blobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncryptedBlobs.def()
    }
}

impl Related<super::encrypted_vault::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncryptedVault.def()
    }
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
