//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::macros::tiny_str_sea_orm_derive;
use sea_orm::entity::prelude::*;
use crate::models;
use tinystr::TinyAsciiStr;

tiny_str_sea_orm_derive!(models::files::PublicId as 16: |s| { Self::new(s) });

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::files::Id,
    #[sea_orm(unique)]
    pub public_id: models::files::PublicId,
    pub folder_id: models::folders::Id,
    pub data_meta_id: models::encrypted_vault::Id,
    pub meta_id: super::encrypted_blobs::Id,
    #[sea_orm(unique)]
    pub storage_path: models::files::StoragePath,
    pub file_size: i64,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "meta_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_blobs: HasOne<super::encrypted_blobs::Entity>,
    #[sea_orm(
        belongs_to,
        from = "data_meta_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_vault: HasOne<super::encrypted_vault::Entity>,
    #[sea_orm(
        belongs_to,
        from = "folder_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub folders: HasOne<super::folders::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
