//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use tinystr::TinyAsciiStr;
use crate::macros::tiny_str_sea_orm_derive;
use sea_orm::entity::prelude::*;
use crate::models;

tiny_str_sea_orm_derive!(models::files::PublicId as 16: |s| { Self::new(s) });

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::files::Id,
    #[sea_orm(unique)]
    pub public_id: models::files::PublicId,
    pub folder_id: models::folders::Id,
    #[sea_orm(column_type = "JsonBinary")]
    pub data_meta: models::encrypted_vault::Model,
    #[sea_orm(column_type = "JsonBinary")]
    pub meta: models::encrypted_blobs::Model,
    #[sea_orm(unique)]
    pub storage_path: models::files::StoragePath,
    pub file_size: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Folders,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for models::files::Model {
    fn from(value: Model) -> Self {
        models::files::Model {
            id: value.id,
            public_id: value.public_id,
            folder_id: value.folder_id,
            data_meta: value.data_meta,
            meta: value.meta,
            storage_path: value.storage_path,
            file_size: value.file_size,
            created_at: value.created_at.to_utc(),
        }
    }
}