//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use tinystr::TinyAsciiStr;
use sea_orm::entity::prelude::*;
use crate::macros::tiny_str_sea_orm_derive;
use crate::models;
use crate::models::folders::FolderName;
use crate::persistence::FromActiveModelExError;

tiny_str_sea_orm_derive!(models::folders::PublicId as 8: |s| { Self::new(s) });

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::folders::Id,
    #[sea_orm(unique)]
    pub public_id: models::folders::PublicId,
    pub encrypted_name: models::encrypted_blobs::Id,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "encrypted_name",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_blobs: HasOne<super::encrypted_blobs::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl TryFrom<ActiveModelEx> for models::folders::Model {
    type Error = FromActiveModelExError;

    fn try_from(mut value: ActiveModelEx) -> Result<Self, Self::Error> {
        Ok(Self {
            id: value.id.take().ok_or(FromActiveModelExError::ValueNotProvided)?,
            public_id: value.public_id.take().ok_or(FromActiveModelExError::ValueNotProvided)?,
            encrypted_name: FolderName::new(value.encrypted_blobs.take().ok_or(FromActiveModelExError::ValueNotProvided)?.try_into()?),
            expired_at: value.expired_at.take().ok_or(FromActiveModelExError::ValueNotProvided)?.map(|e| e.to_utc()),
            created_at: value.created_at.take().ok_or(FromActiveModelExError::ValueNotProvided)?.to_utc(),
        })
    }
}