//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use tinystr::TinyAsciiStr;
use sea_orm::entity::prelude::*;
use crate::macros::tiny_str_sea_orm_derive;
use crate::models;

tiny_str_sea_orm_derive!(models::folders::PublicId as 8: |s| { Self::new(s) });

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::folders::Id,
    #[sea_orm(unique)]
    pub public_id: models::folders::PublicId,
    pub encrypted_name: super::encrypted_blobs::Id,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "encrypted_name",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub encrypted_blobs: HasOne<super::encrypted_blobs::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
