//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::DateTime;
use chrono::FixedOffset;
use tinystr::TinyAsciiStr;
use sea_orm::entity::prelude::*;
use crate::macros::tiny_str_sea_orm_derive;
use crate::models;

tiny_str_sea_orm_derive!(models::folders::PublicId as 8: |s| { Self::new(s) });

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: models::folders::Id,
    #[sea_orm(unique)]
    pub public_id: models::folders::PublicId,
    #[sea_orm(column_type = "JsonBinary")]
    pub encrypted_name: models::folders::FolderName,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for models::folders::Model {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            public_id: value.public_id,
            encrypted_name: value.encrypted_name,
            expired_at: value.expired_at.map(|opt| opt.to_utc()),
            created_at: value.created_at.to_utc(),
        }
    }
}
