//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use crate::persistence::encrypted_blobs::Entity as EncryptedBlobs;
pub use crate::persistence::encrypted_vault::Entity as EncryptedVault;
pub use crate::persistence::files::Entity as Files;
pub use crate::persistence::folders::Entity as Folders;
