//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use crate::models;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "encryption_algo")]
pub enum EncryptionAlgo {
    #[sea_orm(string_value = "aes-256-gcm")]
    Aes256Gcm,
}

impl From<EncryptionAlgo> for models::encrypted_vault::EncryptionAlgo {
    fn from(value: EncryptionAlgo) -> Self {
        match value {
            EncryptionAlgo::Aes256Gcm => Self::Aes256Gcm
        }
    }
}
