//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "encryption_algo")]
pub enum EncryptionAlgo {
    #[sea_orm(string_value = "aes-256-gcm")]
    Aes256Gcm,
}
