//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::macros::tiny_str_sea_orm_derive;
use nutype::nutype;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tinystr::TinyStr16;

#[nutype(
    derive(
        Debug,
        PartialEq,
        Eq,
        Copy,
        Clone,
        Serialize,
        Deserialize,
        Hash,
        Deref,
        Display,
        FromStr
    ),
    derive_unchecked(DeriveValueType)
)]
pub struct Id(i32);

#[nutype(
    derive(
        Debug,
        PartialEq,
        Eq,
        Copy,
        Clone,
        Serialize,
        Deserialize,
        Hash,
        Deref,
        Display,
        FromStr
    ),
    derive_unchecked(DeriveValueType)
)]
pub struct StoragePath(Uuid);

#[nutype(derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    Serialize,
    Deserialize,
    Hash,
    Deref,
    Display,
    FromStr,
))]
pub struct PublicId(TinyStr16);

tiny_str_sea_orm_derive!(PublicId(TinyStr16));

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(unique)]
    pub public_id: PublicId,
    pub folder_id: super::folders::Id,
    #[sea_orm(unique)]
    pub storage_path: StoragePath,
    #[sea_orm(column_type = "Text")]
    pub encrypted_path: String,
    #[sea_orm(column_type = "Text")]
    pub encrypted_mime_type: String,
    #[sea_orm(column_type = "Text")]
    pub encrypted_file_hash: String,
    pub file_size: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Folders,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
