//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use nutype::nutype;
use sea_orm::entity::prelude::*;

#[nutype(
    derive(Debug, PartialEq, Eq, Copy, Clone, Serialize, Deserialize, Hash, Deref, Display, FromStr),
    derive_unchecked(DeriveValueType)
)]
pub struct Id(i32);

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(unique)]
    pub long_id: String,
    pub folder_id: Option<super::folders::Id>,
    #[sea_orm(column_type = "Text")]
    pub encrypted_name: String,
    #[sea_orm(column_type = "Text")]
    pub encrypted_mime_type: String,
    pub encrypted_file_hash: String,
    pub encrypted_file_size: i64,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Folders,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
