//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use nutype::nutype;
use sea_orm::entity::prelude::*;
use tinystr::TinyStr8;
use crate::macros::tiny_str_sea_orm_derive;

#[nutype(
    derive(
        Debug,
        PartialEq,
        Eq,
        Copy,
        Clone,
        Serialize,
        Deserialize,
        Hash,
        Deref,
        Display,
        FromStr
    ),
    derive_unchecked(DeriveValueType)
)]
pub struct Id(i32);

#[nutype(derive(
    Debug,
    PartialEq,
    Eq,
    Clone,
    Serialize,
    Deserialize,
    Hash,
    Deref,
    Display,
    FromStr
))]
pub struct PublicId(TinyStr8);

tiny_str_sea_orm_derive!(PublicId(TinyStr8));

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(unique)]
    pub public_id: PublicId,
    #[sea_orm(column_type = "Text")]
    pub encrypted_name: String,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
