[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
pin-project.workspace = true
futures.workspace = true
derive-new.workspace = true
serde.workspace = true
parking_lot.workspace = true
tokio.workspace = true
async-trait.workspace = true
postcard.workspace = true
amqprs.workspace = true
tracing.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
derivative.workspace = true
