name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: autofix-${{ hashFiles('backend/**/Cargo.lock') }}

      - name: Fix Clippy and Format
        run: |
          cd ./backend
          cargo clippy --fix --workspace --allow-staged --allow-dirty
          cargo fmt --all

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
