on:
  pull_request:
    branches:
      - master
    paths:
      - 'proto/**'
      - 'backend/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Log in to GHCR
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo Registry & sccache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            cargo-registry-cache
            sccache-cache
          key: rust-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            rust-cache-${{ runner.os }}-

      - name: Buildkit Cache Dance
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "cargo-registry": "cargo-registry-cache",
              "sccache": "sccache-cache"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ghcr.io/sqlerrorthing/filebin:backend
          cache-from: type=registry,ref=ghcr.io/sqlerrorthing/filebin:backend-buildcache
          cache-to: type=registry,ref=ghcr.io/sqlerrorthing/filebin:backend-buildcache,mode=max
